### PR TITLE
Fix filled macro

### LINKED ISSUE #134: filled(:integer) returns "int?" error instead of "filled?"
**Bug**

`filled(:integer)` and `filled(:string)` should return the same error message when input is empty

Actual behaviour:

`filled(:string)` returns "must be filled" (`filled?` error)
`filled(:integer)` returns "must be an integer"  (`int?` error)

**To Reproduce**

```ruby
schema = Dry::Schema.Params do
  required(:email).filled(:string)
  required(:user_id).filled(:integer)
end

errors = schema.call(email: '', user_id: '').errors
errors.to_h # => {:email=>["must be filled"], :user_id=>["must be an integer"]}
```

**Expected behavior**

`filled(:integer)` and `filled(:string)` should behave the same and return `filled?` error

**gem version**

```ruby
Dry::Schema::VERSION # => "1.0.2"
```

### PR DESCRIPTION
**Pull request by solnic**
Fixes #134 

This fixes `filled` macro so that it applies `filter(:filled?)` for primitives that are not supported by the corresponding [filled?](https://github.com/dry-rb/dry-logic/blob/master/lib/dry/logic/predicates.rb#L41-L43) predicate. In practice, this means that using `filled` with a type that should be checked if it's filled **before coercion**, will result in applying `filter(:filled?)`.

In example:

``` ruby
dry-schema> s = params { required(:age).filled(:integer) }
=> #<Dry::Schema::Params keys=["age"] rules={:age=>"key?(:age) AND key[age](int?)"}>
dry-schema> s.(age: "").errors.to_h
=> {:age=>["must be filled"]}
dry-schema> s.(age: "foo").errors.to_h
=> {:age=>["must be an integer"]}
dry-schema> s.(age: "30").errors.to_h
=> {}
dry-schema> s.(age: "30").to_h
=> {:age=>30}
```

`JSON` is configured to apply type checks to `nil` instead of `filled?`, so ie:

```ruby
dry-schema> s = json { required(:age).filled(:integer) }
dry-schema> s.(age: nil).errors.to_h
=> {:age=>["must be an integer"]}
```

Contrast that with `Params`:

```
dry-schema> s = params { required(:age).filled(:integer) }
dry-schema> s.(age: nil).errors.to_h
=> {:age=>["must be filled"]}
```

The reason for this different behaviours is that in case of `Params` empty strings are turned into `nil`, which means that a value wasn't filled in, so `filled?` should be applied and provide a useful error message. In case of `JSON` it does not make sense because `nil` means that `null` was passed as the value and it's not allowed because we expect integers. One thing to notice is that using `filled` with numbers in `JSON` schemas is a bit silly, a type check should be enough.

### CODE REVIEW

File: lib/dry/schema/macros/filled.rb [hunk 1]
```diff
@@ -20,11 +29,36 @@ def call(*predicates, **opts, &block)
           end
 
           if opts[:type_spec]
-            value(predicates[0], :filled?, *predicates[1..predicates.size - 1], **opts, &block)
+            if filter?
+              parent.filter(:filled?)
```
Comment (flash-gordon) [inline lib/dry/schema/macros/filled.rb]: `parent` could query the child and call `filter` on itself before combining traces

Comment (flash-gordon) [reply lib/dry/schema/macros/filled.rb]: Something like this (specs passed):
```
diff --git a/lib/dry/schema/macros/dsl.rb b/lib/dry/schema/macros/dsl.rb
index eeed4d0..e3b6da6 100644
--- a/lib/dry/schema/macros/dsl.rb
+++ b/lib/dry/schema/macros/dsl.rb
@@ -66,9 +66,13 @@ module Dry
         # @return [Macros::Core]
         #
         # @api public
-        def filled(*args, &block)
+        def filled(*args, **opts, &block)
           append_macro(Macros::Filled) do |macro|
-            macro.call(*args, &block)
+            defined = macro.call(*args, **opts, &block)
+
+            filter(:filled?) if opts[:type_spec] && defined.filter?
+
+            defined
           end
         end
 
diff --git a/lib/dry/schema/macros/filled.rb b/lib/dry/schema/macros/filled.rb
index 27ecfb0..fdf85c2 100644
--- a/lib/dry/schema/macros/filled.rb
+++ b/lib/dry/schema/macros/filled.rb
@@ -30,7 +30,6 @@ module Dry
 
           if opts[:type_spec]
             if filter?
-              parent.filter(:filled?)
               value(*predicates, **opts, &block)
             else
               value(predicates[0], :filled?, *predicates[1..predicates.size - 1], **opts, &block)
```

File: lib/dry/schema/primitive_inferrer.rb [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+        def visit_enum(node)
+          other, * = node
+          visit(other)
+        end
+
+        # @api private
+        def visit_sum(node)
+          left, right = node
+
+          [visit(left), visit(right)].flatten
```
Comment (flash-gordon) [inline lib/dry/schema/primitive_inferrer.rb]: I would write `flatten(1)` because it should suffice here. If it's not working there must be something wrong

File: lib/dry/schema/primitive_inferrer.rb [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+require 'dry/core/cache'
+
+module Dry
+  module Schema
+    # PrimitiveInferrer is used internally by `Macros::Filled`
+    # for inferring a list of possible primitives that a given
+    # type can handle.
+    #
+    # @api private
+    class PrimitiveInferrer
```
Comment (flash-gordon) [inline lib/dry/schema/primitive_inferrer.rb]: You know, we could even have it in dry-types, wdyt?

File: lib/dry/schema/macros/filled.rb (hunk 1 above)
Comment (solnic) [reply lib/dry/schema/macros/filled.rb]: that's a nice idea, thanks!

File: lib/dry/schema/primitive_inferrer.rb (hunk 2 above)
Comment (solnic) [reply lib/dry/schema/primitive_inferrer.rb]: I think it can be deeply nested when there are deeply nested sums like `Integer | String | Array`, no?

Comment (flash-gordon) [reply lib/dry/schema/primitive_inferrer.rb]: yes but every level has to be balanced with one `visit_sum`, as in `Integer | String | Array` will make two `visit_sum` calls (by the number of `|`)

File: lib/dry/schema/primitive_inferrer.rb (hunk 3 above)
Comment (solnic) [reply lib/dry/schema/primitive_inferrer.rb]: Yes, I would like to see this at some point. There are probably more useful tools we could build into dry-types.

File: lib/dry/schema/macros/filled.rb [hunk 4]
```diff
@@ -20,11 +27,35 @@ def call(*predicates, **opts, &block)
...
+            end
           else
             value(:filled?, *predicates, **opts, &block)
           end
         end
+
+        # @api private
+        def filter?
+          !primitives.include?(NilClass) && processor_config.filter_empty_string
+        end
```
Comment (solnic) [inline lib/dry/schema/macros/filled.rb]: @flash-gordon @timriley what this means is: "if `nil` is NOT an allowed value, and empty strings should be filtered out, then we want to apply `filter(:filled?)`"

File: lib/dry/schema/processor.rb [hunk 5]
```diff
@@ -177,6 +178,20 @@ def rule_applier
         @rule_applier ||= steps.last
       end
       alias_method :to_rule, :rule_applier
+
+      # Check if there are filter rules
+      #
+      # @api private
+      def filter_rules?
+        steps.select { |s| s.is_a?(RuleApplier) }.size > 1
```
Comment (flash-gordon) [inline lib/dry/schema/processor.rb]: hm, `steps.any?`?

File: lib/dry/schema/processor.rb [hunk 6]
```diff
@@ -177,6 +178,20 @@ def rule_applier
...
+      end
+
+      # Check if there are filter rules
+      #
+      # @api private
+      def filter_schema
+        @filter_schema ||= steps.select { |s| s.is_a?(RuleApplier) }.first
```
Comment (flash-gordon) [inline lib/dry/schema/processor.rb]: `steps.find`/`steps.detect`?

File: lib/dry/schema/primitive_inferrer.rb [hunk 7]
```diff
@@ -0,0 +1,98 @@
...
+
+        # @api private
+        def visit_nominal(node)
+          type, _ = node
+          [type]
+        end
+
+        # @api private
+        def visit_hash(_)
+          Hash
```
Comment (flash-gordon) [inline lib/dry/schema/primitive_inferrer.rb]: `visit_*` methods should always return an array, otherwise, `Filled#primitives` may return a class instead of an array of classes

File: lib/dry/schema/processor.rb (hunk 5 above)
Comment (solnic) [reply lib/dry/schema/processor.rb]: @flash-gordon I know it's weird but it's actually correct - if there are more than two rule appliers, it means we've got a filter schema and the final schema

File: lib/dry/schema/macros/filled.rb (hunk 4 above)
Comment (timriley) [reply lib/dry/schema/macros/filled.rb]: I wonder if we can make this clearer (and less needing explanatory comment like the one you left here) by making some of the names more self-descriptive?

e.g. `def handle_via_filter?` for this method, and `expected_primitives` instead of `primitives`?
