### PR TITLE
Unexpected keys errors

### LINKED ISSUE #35: Generating errors for unexpected keys in Hash
I would love to be able to define a schema which generated errors if it was given unexpected keys:

``` ruby
require 'dry/validation'

schema = Dry::Validation.Schema(strict: true) do
  hash? do
    required(:foo).filled(:int?)
    required(:bar).filled(:str?)
  end
end

outcome = schema.call(foo: 1, bar: "two", baz: 3.0)
p outcome.messages # => {:baz=>["is not allowed"]}
```

This is really important for defining a public JSON API where you want to reject invalid user input.

### PR DESCRIPTION
**Pull request by solnic**
This adds a new processor step called `:key_validator` which validates if there are no unexpected keys. This works with both nested hashes and arrays with hashes.

```ruby
require 'dry/schema'

UserSchema = Dry::Schema.Params do
  config.validate_keys = true

  required(:name).filled(:string)

  required(:address).hash do
    required(:city).filled(:string)
    required(:zipcode).filled(:string)
  end

  required(:roles).array(:hash) do
    required(:name).filled(:string)
  end
end

input = {
  foo: 'unexpected',
  name: 'Jane',
  address: { bar: 'unexpected', city: 'NYC', zipcode: '1234' },
  roles: [{ name: 'admin' }, { name: 'editor', foo: 'unexpected' }]
}

UserSchema.(input).errors.to_h
# {
#  :foo=>["is not allowed"],
#  :address=>{:bar=>["is not allowed"]},
#  :roles=>{1=>{:foo=>["is not allowed"]}}
# }
```

Closes #35 

[changelog]

added: "You can now validate keys by setting `config.validate_keys = true". When enabled, schemas will provide error messages about unexpected keys in the input (issue #35 closed via #260) (@solnic)"

### CODE REVIEW

File: lib/dry/schema/key_validator.rb [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+        key_paths = key_map.to_dot_notation
+
+        input_paths.each do |path|
+          key = path.gsub(%r[\[\d+\]], '[]')
+          arr = path.gsub(/\[\d+\]/) { |m| ".#{m[1]}" }
+
+          unless key_paths.include?(key)
+            result.add_error(
+              [:unexpected_key, [
+                arr.split(DOT).map { |s| s =~ /\d+/ ? s.to_i : s.to_sym },
```
Comment (flash-gordon) [inline lib/dry/schema/key_validator.rb]: should be `/\A\d+\z/` _I think_

File: lib/dry/schema/key_validator.rb [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+        end
+
+        result
+      end
+
+      private
+
+      # @api private
+      def key_paths(hash)
+        hash.keys.flat_map { |key|
```
Comment (flash-gordon) [inline lib/dry/schema/key_validator.rb]: `hash.flat_map { |key, value|`
